services:
  dashboard:
    build: ./apps/dashboard-app
    ports:
      - "3000:3000"

  service1:
    build: ./apps/microservice-based-system/service1
    ports:
      - "3001:3001"
    depends_on:
      - otel-collector

  service2:
    build: ./apps/microservice-based-system/service2
    ports:
      - "3002:3002"
    depends_on:
      - otel-collector

  service3:
    build: ./apps/microservice-based-system/service3
    ports:
      - "3003:3003"
    depends_on:
      - otel-collector

  otel-collector:
    build: ./opentelemetry
    ports:
      - "4317:4317"
    depends_on:
      - clickhouse

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
