services:
  dashboard:
    build:
      context: ./apps/dashboard-app
    ports:
      - "3000:3000"

  service1:
    build:
      context: ./apps/microservice-based-system/service1
    ports:
      - "3001:3001"

  service2:
    build:
      context: ./apps/microservice-based-system/service2
    ports:
      - "3002:3002"

  service3:
    build:
      context: ./apps/microservice-based-system/service3
    ports:
      - "3003:3003"

  otel-collector:
    image: chainguard/opentelemetry-collector-contrib:latest
    volumes:
      - ./opentelemetry/otel-collector-config.yaml:/otel-local-config.yaml
    command: ["--config", "/otel-local-config.yaml"]
    ports:
      - "4317:4317"  # gRPC
      - "55681:55681"  # HTTP
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
      - "8123:8123"
 

     